apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-template
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: message
            default: "Hello from Workflow Template!"
      container:
        image: alpine:3.14
        command: [echo]
        args: ["{{inputs.parameters.message}}"]
